### ISSUE TITLE
Evernote iOS SDK crash at Re-authorise page

### ISSUE THREAD

**Issue by siva7sanakr** [evernote/evernote-cloud-sdk-ios#93] opened 2015-05-27 09:31 UTC
I have implemented the SDK integration for my iOS app, where web view is pushed for login and authorise the account. In this screen user can select the authorisation time period in popover, selecting the option from list multiple time causing the app to crash with error,

Application tried to represent an active popover presentation: <UIPopoverPresentationController: 0x18f66470>

 *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x18f79b60>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'

*** First throw call stack:
(0x24e8d49f 0x32945c8b 0x289ee59f 0x2861ce03 0x2861badb 0x283c9a25 0x2834582b 0x24e53d95 0x24e51453 0x24e5185b 0x24d9f3c1 0x24d9f1d3 0x2c1740a9 0x283aefa1 0x2ee21 0x32ec5aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by everic** [comment] 2015-05-27 19:26
Hi @siva7sanakr 
Can you do me a favor by providing a screen recording to show where it crashed? It would help a lot. Thank you.

**Comment by siva7sanakr** [comment] 2015-06-02 10:19
I have attached the video in Dropbox https://www.dropbox.com/s/kdp5grexvugrk7c/EvernoteCrash.mov?dl=0 . Here are the steps to reproduce it,
1) Install any iPad app that using Evernote iOS SDK (Only iPad apps)
2) Goto to Evernote login page for authentication and give valid credentials.
3) In authorisation time period selection drop down list, select dropdown button multiple times to open and close it. App getting crash.

**Comment by everic** [comment] 2015-06-02 21:50
Hi @siva7sanakr 
Thank you for your video. It helped a lot.

However, I could not reproduce with the SDK sample app on iOS 8.3. What versions of iOS are you using? Can you try if you can repro on iOS 8.3? And, can you share the authentication code snippet in your app? Can you compile the sample app with the SDK to see if it crashes?

Thank you.

**Comment by siva7sanakr** [comment] 2015-06-04 12:27
We will be verifying it on iOS 8.3 devices. Mean while can I get the details that minimum OS version that this SDK is supported and the same crash issue found in it.

Thanks.

**Comment by everic** [comment] 2015-06-08 23:35
The minimum OS version this SDK support is iOS 7.0. But there could be bugs in iOS or the SDK or your application code that caused the crash. Please let me know the answers to my question and it will help us resolve the issue much faster. Thank you.

**Comment by siva7sanakr** [comment] 2015-06-11 06:54
Hi @everic 

We have verified the crash issue in iOS 8.3 device and it is working fine, but getting the same crash issue in iOS version lower than 8.3.

**Comment by everic** [comment] 2015-06-11 20:57
The SDK sample app does not have this crashing issue with either 8.3 or 8.2. Can you do us a favor by providing your sample project that will lead to this crash? Thank you.

**Comment by siva7sanakr** [comment] 2015-06-15 12:47
Hi @everic 

Here is the link for my sample Evernote app
https://www.dropbox.com/s/ovvdxtnfzp0397p/EvernoteSample.zip?dl=0
Note: Run this app in iPad device or simulator. Pointing to sandbox or production is also causing this crash.

**Comment by everic** [comment] 2015-06-15 21:52
Hello @siva7sanakr 
Thank you for your help in investigating this issue. Your effort helped us a lot.

I believe this is an Apple issue. People have filed radars for this and this is already resolved in iOS 8.3 http://openradar.appspot.com/19469574#aglvcGVucmFkYXJyFAsSB0NvbW1lbnQYgICAoOugswoM

Thanks!

**Closed by everic** 2015-06-15 21:52 UTC
