### ISSUE TITLE
modifying code to support shared keychain resulted in today's extension not able to findNote randomly

### ISSUE THREAD

**Issue by Tianlye** [evernote/evernote-cloud-sdk-ios#65] opened 2014-11-27 20:18 UTC
As the subject, there are times whereby the today extension is not able to findNote and gave error 
(Error Domain error 5.)" {EDAM Error Code=3, parameter=authenticationToken}. 

I have managed to share the keychain but modifying some of the codes in the sdks. However, the above error just appear randomly throughout the use of my app. 
Please help. 

Consumer key is : tianlye-0777

**Comment by everic** [comment] 2015-01-03 00:53
What API did you use in your today extension to findNote? Can you elaborate on it? What are you implementing with the Evernote iOS SDK? Thank you.

**Comment by everic** [comment] 2015-01-22 21:39
duplicate of https://github.com/evernote/evernote-cloud-sdk-ios/issues/72

**Closed by everic** 2015-01-22 21:39 UTC
Labels: waiting for info
