### ISSUE TITLE
CocoaPod import with swift doesn't work

### ISSUE THREAD

**Issue by Chaosspeeder** [evernote/evernote-cloud-sdk-ios#113] opened 2015-10-07 04:33 UTC
I want to use the new evernote-cloud-sdk-ios as a framework with CocoaPods but it doesn't work.
1. There are non-modular header file usages in ENXMLUtils.h and ENXMLSaxParser.h
   # import <libxml/xmlstring.h>
   # import <libxml/tree.h>

2 The mysteries error of not building "Objective-C" module "evernote_cloud_sdk_ios" 

And yes, I have used CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES=YES

![bildschirmfoto 2015-10-07 um 06 25 59](https://cloud.githubusercontent.com/assets/7107433/10329099/979048d4-6cbc-11e5-860d-e3e31f022df3.png)

Please fix or give me hints for workarounds.

**Comment by nervlord** [comment] 2015-10-07 21:48
I too had a similar issue and spent a fair amount of time trying to solve. I tried all sort of things it's not even funny. 

The issue is <libxml/tree.h> and <libxml/xmlstring.h> which are part of the libxml library, i tried finding the path to libxml2.dynlib and linking that and that didn't do it, i tried embedded binaries, i tried adding something to my module map. i might have to get desperate and rewrite the same bits of the tree.h file and xmlstring.h file that evernote uses, but it depends how many it requires.

**Comment by Chaosspeeder** [comment] 2015-10-08 05:41
This was my third attempt to update my old Evernote SDK to the new cloud api SDK. It's the task of People of Evernote in my opinion. Swift is established and they should improve their SDK to work seamlessly with Swift and Cocoapods.

**Comment by Limon-catch** [comment] 2015-11-29 08:31
+1

**Comment by jimdusseau** [comment] 2015-11-29 19:54
As of 2.0.5, there's been an issue with Cocoa pods integration in general. Did anyone try this with Objective-C to discern whether that's the core issue?

**Comment by jimdusseau** [comment] 2015-11-29 20:53
Can you try out 2.0.6 and close this issue if it fixes things for you?

**Comment by Limon-catch** [comment] 2015-11-30 03:29
Did you update 2.0.6 to CocoaPods?

**Comment by jimdusseau** [comment] 2015-11-30 03:32
Unfortunately, I don't have access. We'll be filing a claim to get access tomorrow. For now, I'd appreciate if someone verified that what I've changed is working for them by pointing cocoa pods directly at this github project

**Comment by Limon-catch** [comment] 2015-11-30 05:00
I installed 2.0.6, but ![](https://raw.githubusercontent.com/Limon-catch/EvernoteSimple/master/image/hearder_error.png)
I create a [repository](https://github.com/Limon-catch/EvernoteSimple). You can test it.

**Comment by jimdusseau** [comment] 2015-11-30 20:57
@Limon-catch I was able to make this work with f367ada. In your project, I removed the import from the bridging header and added "import evernote_cloud_sdk_ios" in ViewController.swift. Please let me know if this works so I can tag it as 2.0.7.

**Comment by Limon-catch** [comment] 2015-12-02 16:09
Sorry, @jimdusseau , I come late. It works. Thanks :)

**Closed** 2017-03-16 20:31 UTC
